#include <stdio.h>
#include <stdlib.h>
#include "kvdb.h"
int main(){
kvdb_t *db=malloc(sizeof(kvdb_t));
kvdb_open(db,DB_FILE);
/* srand seed: 920403885*/
char* mystr;
kvdb_put(db, "BBB", "qkd");
kvdb_put(db, "III", "r");
kvdb_put(db, "OOO", "veuynzplspgiawneuhlyidwmefktfm");
kvdb_put(db, "III", "fxiwarygker");
printf("%s\n", (mystr = kvdb_get(db, "OOO")) == NULL ? "(null)" : mystr);
kvdb_put(db, "HHH", "lmp");
kvdb_put(db, "EEE", "rbjagtdjpq");
kvdb_put(db, "CCC", "bbporyjmci");
kvdb_put(db, "OOO", "bxrhtzcoiqpvexe");
kvdb_put(db, "LLL", "vzrzwutcmeivulj");
printf("%s\n", (mystr = kvdb_get(db, "OOO")) == NULL ? "(null)" : mystr);
kvdb_put(db, "KKK", "wbuxj");
kvdb_put(db, "EEE", "rdyiunmmzy");
kvdb_put(db, "AAA", "uh");
kvdb_put(db, "CCC", "hcbqycygx");
kvdb_put(db, "PPP", "mcoeketjkvcnuntrxixbjzsasqjg");
printf("%s\n", (mystr = kvdb_get(db, "BBB")) == NULL ? "(null)" : mystr);
kvdb_put(db, "III", "nuynqijgxakfddmrwiakz");
kvdb_put(db, "HHH", "inczbyd");
kvdb_put(db, "FFF", "pfkajsqifzpulcatrivdo");
kvdb_put(db, "KKK", "wvyrhgiqfugttnfcnemffbhbsueuw");
printf("%s\n", (mystr = kvdb_get(db, "AAA")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "PPP")) == NULL ? "(null)" : mystr);
kvdb_put(db, "GGG", "gqwwbddvqqan");
kvdb_put(db, "FFF", "baxdjlponmoxkydz");
kvdb_put(db, "MMM", "pzoqcdzfedlghywuve");
printf("%s\n", (mystr = kvdb_get(db, "CCC")) == NULL ? "(null)" : mystr);
kvdb_put(db, "AAA", "zzxewspuvvqdqnzkmavvwgj");
printf("%s\n", (mystr = kvdb_get(db, "FFF")) == NULL ? "(null)" : mystr);
kvdb_put(db, "NNN", "wgsafnesy");
printf("%s\n", (mystr = kvdb_get(db, "EEE")) == NULL ? "(null)" : mystr);
kvdb_put(db, "III", "xntbqgxvgoppogeczad");
kvdb_put(db, "PPP", "nvjyfclz");
printf("%s\n", (mystr = kvdb_get(db, "GGG")) == NULL ? "(null)" : mystr);
kvdb_put(db, "GGG", "wvyrhgiqfugttnfcnemffbhbsueuw");
kvdb_put(db, "BBB", "kngfpiaj");
printf("%s\n", (mystr = kvdb_get(db, "HHH")) == NULL ? "(null)" : mystr);
kvdb_put(db, "HHH", "cxybtwfwjopwtb");
printf("%s\n", (mystr = kvdb_get(db, "KKK")) == NULL ? "(null)" : mystr);
kvdb_put(db, "EEE", "sjqdbcjroyyabiursz");
kvdb_put(db, "GGG", "rioqv");
kvdb_put(db, "OOO", "tszhznlzrypemamvlgmvuqmpwdstuo");
kvdb_put(db, "MMM", "knltpvzhtaxpvsrfgfnyvwgsi");
kvdb_put(db, "DDD", "hxrsqdnboanvqcurb");
printf("%s\n", (mystr = kvdb_get(db, "LLL")) == NULL ? "(null)" : mystr);
kvdb_put(db, "FFF", "jljpfscjqnxuckdigapeuypd");
printf("%s\n", (mystr = kvdb_get(db, "GGG")) == NULL ? "(null)" : mystr);
kvdb_put(db, "EEE", "wfbroxrnhewsjhnididhmhcms");
printf("%s\n", (mystr = kvdb_get(db, "NNN")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "BBB")) == NULL ? "(null)" : mystr);
kvdb_put(db, "LLL", "wfbroxrnhewsjhnididhmhcms");
kvdb_put(db, "KKK", "stmswe");
kvdb_put(db, "III", "atpxnazzsymtrk");
kvdb_put(db, "PPP", "pfkajsqifzpulcatrivdo");
kvdb_put(db, "PPP", "avnflvxascyylhwecohppxp");
printf("%s\n", (mystr = kvdb_get(db, "OOO")) == NULL ? "(null)" : mystr);
kvdb_put(db, "MMM", "yiiyreddxpruue");
printf("%s\n", (mystr = kvdb_get(db, "PPP")) == NULL ? "(null)" : mystr);
kvdb_put(db, "AAA", "rkempiffmjpgxptpsbfjxzyxifwgae");
kvdb_put(db, "KKK", "zfcrkniuazwslpxmvmghkiytq");
kvdb_put(db, "KKK", "hcbqycygx");
kvdb_put(db, "FFF", "drhfrgszexbsgsjghpb");
kvdb_put(db, "AAA", "nuynqijgxakfddmrwiakz");
kvdb_put(db, "III", "sajtc");
kvdb_put(db, "HHH", "steecsajgdphq");
kvdb_put(db, "GGG", "qzyoployfgcrkdlwctlziealw");
kvdb_put(db, "EEE", "kqao");
kvdb_put(db, "DDD", "xmvkyjjzvqcxvlxdewhtvwtwyjjujnv");
kvdb_put(db, "JJJ", "diayviwwkinbmsoicde");
kvdb_put(db, "EEE", "duvd");
kvdb_put(db, "NNN", "tyuqyvxkkulvlnogt");
kvdb_put(db, "CCC", "hdhgcngsgaagaigrwao");
kvdb_put(db, "CCC", "gqknwn");
kvdb_put(db, "KKK", "azbnlocyjtwicpkzgfrak");
kvdb_put(db, "BBB", "uvpfkxdocyrygewyjxyomaocaqxzuo");
kvdb_put(db, "III", "atpxnazzsymtrk");
printf("%s\n", (mystr = kvdb_get(db, "MMM")) == NULL ? "(null)" : mystr);
kvdb_put(db, "NNN", "ulolpcfh");
kvdb_put(db, "HHH", "flqklrpnkccswfuuxfkwthjzqvh");
kvdb_put(db, "AAA", "mngnfjwitk");
kvdb_put(db, "CCC", "qzgvmwgypxnzbqsavmuutg");
kvdb_put(db, "NNN", "zfcrkniuazwslpxmvmghkiytq");
printf("%s\n", (mystr = kvdb_get(db, "KKK")) == NULL ? "(null)" : mystr);
kvdb_put(db, "BBB", "qlvgi");
printf("%s\n", (mystr = kvdb_get(db, "LLL")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "BBB")) == NULL ? "(null)" : mystr);
kvdb_put(db, "KKK", "mcoeketjkvcnuntrxixbjzsasqjg");
kvdb_put(db, "MMM", "l");
kvdb_put(db, "LLL", "cacgsmdwyah");
kvdb_put(db, "BBB", "kczulyipvpqbbs");
printf("%s\n", (mystr = kvdb_get(db, "AAA")) == NULL ? "(null)" : mystr);
kvdb_put(db, "HHH", "rbjagtdjpq");
kvdb_put(db, "BBB", "dvcquzomjxwchtfcrnee");
kvdb_put(db, "KKK", "debgupiebkcwgihzzsmjggctxpimx");
kvdb_put(db, "OOO", "jmxqnqsajplpvlkpfwnhdamjcjo");
kvdb_put(db, "AAA", "wgsafnesy");
kvdb_put(db, "BBB", "fyiok");
printf("%s\n", (mystr = kvdb_get(db, "BBB")) == NULL ? "(null)" : mystr);
kvdb_put(db, "JJJ", "iuqpoajgcxspb");
kvdb_put(db, "EEE", "atpxnazzsymtrk");
printf("%s\n", (mystr = kvdb_get(db, "FFF")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "EEE")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "NNN")) == NULL ? "(null)" : mystr);
kvdb_put(db, "GGG", "rkdzam");
kvdb_put(db, "DDD", "tmmuc");
kvdb_put(db, "AAA", "mo");
kvdb_put(db, "NNN", "jpkirvhayswfeycqoo");
kvdb_put(db, "GGG", "snkfnerdgzawkhdqluymiaybjgcu");
kvdb_put(db, "LLL", "umyuypqrbybfbekvfvhhogpadlv");
printf("%s\n", (mystr = kvdb_get(db, "GGG")) == NULL ? "(null)" : mystr);
kvdb_put(db, "KKK", "hxrsqdnboanvqcurb");
kvdb_put(db, "LLL", "nvhmlbzca");
kvdb_put(db, "CCC", "kwlquszkzrkec");
kvdb_put(db, "AAA", "aa");
kvdb_put(db, "GGG", "xmvkyjjzvqcxvlxdewhtvwtwyjjujnv");
kvdb_put(db, "BBB", "tvakolgsqjixmpgrem");
kvdb_put(db, "NNN", "rfaswtz");
kvdb_put(db, "JJJ", "ovjpcycagbtjxmbzvmiihcqgsech");
kvdb_put(db, "III", "rkempiffmjpgxptpsbfjxzyxifwgae");
printf("%s\n", (mystr = kvdb_get(db, "GGG")) == NULL ? "(null)" : mystr);
kvdb_put(db, "AAA", "ovjpcycagbtjxmbzvmiihcqgsech");
kvdb_put(db, "PPP", "fwzsxsetg");
kvdb_put(db, "JJJ", "qlvgi");
printf("%s\n", (mystr = kvdb_get(db, "III")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "AAA")) == NULL ? "(null)" : mystr);
kvdb_put(db, "PPP", "qsqn");
kvdb_put(db, "MMM", "xmvkyjjzvqcxvlxdewhtvwtwyjjujnv");
kvdb_put(db, "KKK", "pzoqcdzfedlghywuve");
kvdb_close(db);
return 0;
}