#include <stdio.h>
#include <stdlib.h>
#include "kvdb.h"
int main(){
kvdb_t *db=malloc(sizeof(kvdb_t));
kvdb_open(db,DB_FILE);
/* srand seed: 467262508*/
char* mystr;
kvdb_put(db, "BBB", "mcrowlixeohfkoxetk");
kvdb_put(db, "CCC", "lfcq");
kvdb_put(db, "KKK", "xxdgrbrgrrxsadarsibg");
kvdb_put(db, "KKK", "bglgiutmamhnbgfolqqyo");
printf("%s\n", (mystr = kvdb_get(db, "KKK")) == NULL ? "(null)" : mystr);
kvdb_put(db, "OOO", "en");
kvdb_put(db, "KKK", "dyt");
kvdb_put(db, "III", "x");
kvdb_put(db, "CCC", "x");
kvdb_put(db, "DDD", "npceqwecginulpqrpvuxlthnru");
printf("%s\n", (mystr = kvdb_get(db, "OOO")) == NULL ? "(null)" : mystr);
kvdb_put(db, "MMM", "tjuypdrdkzcbmyqpwsumxpzfiubnga");
printf("%s\n", (mystr = kvdb_get(db, "III")) == NULL ? "(null)" : mystr);
kvdb_put(db, "OOO", "dolhtgyvefcmejqxqyuylzmzpxlo");
kvdb_put(db, "KKK", "qlwe");
kvdb_put(db, "GGG", "nevbxfknuowauyltasyyvpabdxoca");
kvdb_put(db, "EEE", "sns");
kvdb_put(db, "CCC", "igiyhqwr");
kvdb_put(db, "DDD", "pknttaoukt");
kvdb_put(db, "JJJ", "mvw");
kvdb_put(db, "KKK", "bglgiutmamhnbgfolqqyo");
kvdb_put(db, "OOO", "lojhvzeha");
printf("%s\n", (mystr = kvdb_get(db, "BBB")) == NULL ? "(null)" : mystr);
kvdb_put(db, "LLL", "peeuia");
printf("%s\n", (mystr = kvdb_get(db, "CCC")) == NULL ? "(null)" : mystr);
kvdb_put(db, "III", "xlsindqde");
kvdb_put(db, "PPP", "vpzhzbajfsboh");
printf("%s\n", (mystr = kvdb_get(db, "OOO")) == NULL ? "(null)" : mystr);
kvdb_put(db, "DDD", "cvqngfvarbartfqsj");
kvdb_put(db, "KKK", "uogatbubdjrpr");
printf("%s\n", (mystr = kvdb_get(db, "EEE")) == NULL ? "(null)" : mystr);
kvdb_put(db, "FFF", "oumk");
kvdb_put(db, "PPP", "tqny");
kvdb_put(db, "EEE", "zioprzlzupb");
kvdb_put(db, "AAA", "wbpdamjkmzzpsgt");
printf("%s\n", (mystr = kvdb_get(db, "EEE")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "PPP")) == NULL ? "(null)" : mystr);
kvdb_put(db, "PPP", "uwzmporko");
printf("%s\n", (mystr = kvdb_get(db, "JJJ")) == NULL ? "(null)" : mystr);
kvdb_put(db, "JJJ", "ltzbmojjugscavvpgbqjanuv");
kvdb_put(db, "III", "vnjyancwimjscatbwosnwfb");
printf("%s\n", (mystr = kvdb_get(db, "KKK")) == NULL ? "(null)" : mystr);
kvdb_put(db, "FFF", "dqpgqjctvb");
kvdb_put(db, "GGG", "v");
kvdb_put(db, "BBB", "x");
printf("%s\n", (mystr = kvdb_get(db, "FFF")) == NULL ? "(null)" : mystr);
kvdb_put(db, "AAA", "lojhvzeha");
printf("%s\n", (mystr = kvdb_get(db, "GGG")) == NULL ? "(null)" : mystr);
kvdb_put(db, "MMM", "oumk");
kvdb_put(db, "LLL", "v");
kvdb_put(db, "OOO", "mcxgibaeaxbttzsqkhaqbognxboc");
kvdb_put(db, "FFF", "vbklfrknkatbtichtshn");
kvdb_put(db, "HHH", "mrdftffijnduwl");
printf("%s\n", (mystr = kvdb_get(db, "MMM")) == NULL ? "(null)" : mystr);
kvdb_put(db, "JJJ", "jojaenpkansakeeihvpaq");
printf("%s\n", (mystr = kvdb_get(db, "FFF")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "OOO")) == NULL ? "(null)" : mystr);
kvdb_put(db, "KKK", "qn");
kvdb_put(db, "PPP", "davyvxejqnucizxudhulfq");
kvdb_put(db, "EEE", "fvztttzghodixrzohcufwowb");
kvdb_put(db, "III", "qpaxdommg");
kvdb_put(db, "FFF", "pnbnryubnqplqkjbfmwfmrvnvakjem");
kvdb_put(db, "EEE", "jceygpwh");
printf("%s\n", (mystr = kvdb_get(db, "JJJ")) == NULL ? "(null)" : mystr);
kvdb_put(db, "III", "tyktvunvefp");
kvdb_put(db, "III", "cvqngfvarbartfqsj");
kvdb_put(db, "EEE", "vnjyancwimjscatbwosnwfb");
printf("%s\n", (mystr = kvdb_get(db, "DDD")) == NULL ? "(null)" : mystr);
kvdb_put(db, "CCC", "kvmbbbnundtjvcpagfcluxveosmuc");
kvdb_put(db, "BBB", "mmhczqxf");
printf("%s\n", (mystr = kvdb_get(db, "FFF")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "KKK")) == NULL ? "(null)" : mystr);
kvdb_put(db, "CCC", "xysxma");
kvdb_put(db, "KKK", "nhfhmemowlvbedkjeeeqo");
kvdb_put(db, "III", "fmn");
printf("%s\n", (mystr = kvdb_get(db, "PPP")) == NULL ? "(null)" : mystr);
kvdb_put(db, "GGG", "redhwuh");
kvdb_put(db, "GGG", "tmxpcbt");
kvdb_put(db, "LLL", "gragzsnybvsgzpcrduqyyvwjvgmobdj");
kvdb_put(db, "GGG", "fzfxwdfciojfw");
kvdb_put(db, "HHH", "qxgkxbksywfegdyu");
printf("%s\n", (mystr = kvdb_get(db, "EEE")) == NULL ? "(null)" : mystr);
kvdb_put(db, "III", "nfokpozbqutfd");
kvdb_put(db, "KKK", "mvw");
printf("%s\n", (mystr = kvdb_get(db, "GGG")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "KKK")) == NULL ? "(null)" : mystr);
kvdb_put(db, "NNN", "ucucayshfcwe");
kvdb_put(db, "LLL", "mfjpy");
printf("%s\n", (mystr = kvdb_get(db, "AAA")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "III")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "CCC")) == NULL ? "(null)" : mystr);
kvdb_put(db, "HHH", "ynptirkepw");
kvdb_put(db, "LLL", "iugyujoqcuubughckhgtdrrnjkjvetm");
printf("%s\n", (mystr = kvdb_get(db, "LLL")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "BBB")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "HHH")) == NULL ? "(null)" : mystr);
kvdb_put(db, "NNN", "vbrlptghmgcftjqrmodlbdygsh");
printf("%s\n", (mystr = kvdb_get(db, "NNN")) == NULL ? "(null)" : mystr);
kvdb_put(db, "PPP", "jolsatatxkmfiysldrmveopnktqc");
printf("%s\n", (mystr = kvdb_get(db, "PPP")) == NULL ? "(null)" : mystr);
kvdb_put(db, "MMM", "pknttaoukt");
printf("%s\n", (mystr = kvdb_get(db, "MMM")) == NULL ? "(null)" : mystr);
kvdb_put(db, "GGG", "vpzhzbajfsboh");
kvdb_put(db, "OOO", "atekeorkotnafiwirndsacrjv");
kvdb_put(db, "OOO", "blxgmhgoejnfzioawzviubyuvan");
kvdb_put(db, "DDD", "uwktjknfcjlcgstlpzqleic");
printf("%s\n", (mystr = kvdb_get(db, "GGG")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "OOO")) == NULL ? "(null)" : mystr);
kvdb_put(db, "NNN", "iugyujoqcuubughckhgtdrrnjkjvetm");
kvdb_put(db, "NNN", "cvqngfvarbartfqsj");
kvdb_put(db, "HHH", "pnbnryubnqplqkjbfmwfmrvnvakjem");
printf("%s\n", (mystr = kvdb_get(db, "DDD")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "HHH")) == NULL ? "(null)" : mystr);
kvdb_put(db, "PPP", "ssftgfasoggtrvareotcnpmks");
printf("%s\n", (mystr = kvdb_get(db, "NNN")) == NULL ? "(null)" : mystr);
kvdb_put(db, "LLL", "sktulfjfiavhmulcgfqohmrdnvn");
printf("%s\n", (mystr = kvdb_get(db, "LLL")) == NULL ? "(null)" : mystr);
kvdb_put(db, "DDD", "jmvzk");
kvdb_put(db, "FFF", "ncwckthm");
kvdb_put(db, "DDD", "wbpdamjkmzzpsgt");
kvdb_put(db, "EEE", "bglgiutmamhnbgfolqqyo");
kvdb_put(db, "DDD", "zjt");
kvdb_put(db, "LLL", "sns");
printf("%s\n", (mystr = kvdb_get(db, "DDD")) == NULL ? "(null)" : mystr);
kvdb_put(db, "GGG", "ltzbmojjugscavvpgbqjanuv");
printf("%s\n", (mystr = kvdb_get(db, "EEE")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "LLL")) == NULL ? "(null)" : mystr);
printf("%s\n", (mystr = kvdb_get(db, "FFF")) == NULL ? "(null)" : mystr);
kvdb_close(db);
return 0;
}